#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#
#   The name of the custom HTTP header must be X-Served-By
#   Thee value of the custom HTTP header must be the hostname of the server Nginx is running on
#   A 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the 
#   requirements asked in this task

apt update -y
apt install nginx -y
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

echo "server {
        listen  80;
        listen  [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root    /etc/nginx/html;
        index   index.html index.htm;
}" > /etc/nginx/sites-available/default

tag="\\\n\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/www.google.com;\n\t}"
sed -i "6i $tag" /etc/nginx/sites-available/default
touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
var="\\\n\terror_page 404 /404.html;\n\tlocation /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "10i $var" /etc/nginx/sites-available/default

service nginx restart
