#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
#Ubuntu Focal(20.04LTS)
#version: 2.0 stable LTS
#
#Requirements:
#
#    Configure HAproxy so that it send traffic to web-01 and web-02
#    Distribute requests using a roundrobin algorithm
#    Make sure that HAproxy can be managed via an init script
#    Make sure that your servers are configured with the right
#    hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get -y install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/my_original_copy_haproxy.cfg

var="\\\nfrontend web_front\n\tbind *:80\n\tmode http\n\tdefault_backend web_backend\n\nbackend web_backend\n\tbalance roundrobin\n\tserver web-01 100.26.234.180 check\n\tserver web-02 34.227.94.71 check\n"
sed -i "$ a$var" /etc/haproxy/haproxy.cfg

service haproxy start
